travis:
  secure:
    BINSTAR_TOKEN: ot06b3zxSATcqkjGUKi1ITEx7XkcbJp/dLngwER6s5XXASwEIKErUdN21uU1nyjzAQpHy3+XRijyP+sccbfvchrNYrBZWzqL/gFD32qOkZ40HgCD08iVEtCZTtf1ek5Kc/dsDLu5+F2vDe6nZJ/PVWt9vg7VHt3JyTJFjOM/hbpWZHQ3ED3zfzWMO4cj5Y/+v4ibAgQaKb7g0DEK8QloDXnyLk+3UcHXN1favDKKm1OccWBPtjj8X+2vhm+3bgWr3F6kInvaZ+Kg5N3FFYZAUitNDVe5K4uOxPH7kAgW6uj2AYUjT3fvBCh8NfpiP23ty9yZGObU7ZeBtvwcjoxXATvyA1ekMtBmfR0GJtNSmB7VftgB9sRxSTM2ikcMr6np3z09gIQSGtkyQzLIhIplC3mUFdt8NifuNgvu1oL7JDKf2xvISqzUaIVjmhahGrEGlIkdRVZUjpsAyyV366XrHrFEzPfn+LBhhkIxnkU29lYyr6yjfs8bPALDubsxYdPfX8RAQKqHgALVTgPvSMM68NLo9A6QC1K0PImGhkNkhRjakspWatGSuWpR1ixxx+hvFRRVjI0fOxRDKPZbyS637o275ioV+wG/LQqemlWOuT0N3TSRaI8iNosp7+03B4AX9JCmDLMnlneTo2zxha34eqpOwyiqIJ9v+izqzKnihts=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
  linux_aarch64: default
  linux_ppc64le: default
conda_forge_output_validation: true
