build_platform:
   osx_arm64: osx_64
 conda_forge_output_validation: true
 provider:		 provider:
   win: azure		
   linux_aarch64: default		   linux_aarch64: default
   linux_ppc64le: default		   linux_ppc64le: default
 conda_forge_output_validation: true		   win: azure
 test_on_native_only: true
